apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/generated/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: serving-grafana
  name: serving-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: serving-grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o kubernetes/generated/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: serving-grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - env:
            - name: GF_INSTALL_PLUGINS
              value: yesoreyeram-infinity-datasource,ae3e-plotly-panel
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          image: grafana/grafana:latest
          name: serving-grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/dashboards
              name: serving-grafana-cm0
            - mountPath: /etc/grafana/provisioning/datasources
              name: serving-grafana-cm1
            - mountPath: /var/lib/grafana
              name: serving-grafana-data
      restartPolicy: Always
      volumes:
        - configMap:
            name: serving-grafana-cm0
          name: serving-grafana-cm0
        - configMap:
            name: serving-grafana-cm1
          name: serving-grafana-cm1
        - name: serving-grafana-data
          persistentVolumeClaim:
            claimName: serving-grafana-data
