apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: speed-cassandra-data
  name: speed-cassandra-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
