apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: speed-spark-checkpoints
  name: speed-spark-checkpoints
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
