apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://serving-prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: infinity
    access: proxy
    isDefault: true
    editable: false
